//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeBot.UrbanDictionary {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:UrbanSearch", ConfigurationName="UrbanDictionary.UrbanSearchPortType")]
    public interface UrbanSearchPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.urbandictionary.com/soap/lookup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Definition[] lookup(string key, string term);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.urbandictionary.com/soap/nearby", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string[] nearby(string key, string term);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.urbandictionary.com/soap/count_definitions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        [return: System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        string count_definitions(string key, string term);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.urbandictionary.com/soap/get_daily_definition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SkypeBot.UrbanDictionary.Definition get_daily_definition();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.urbandictionary.com/soap/get_random_definition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SkypeBot.UrbanDictionary.Definition get_random_definition(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.urbandictionary.com/soap/get_related_tags", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string[] get_related_tags(string key, string tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.urbandictionary.com/soap/verify_key", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool verify_key(string key);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:UrbanSearch")]
    public partial class Definition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wordField;
        
        private string definitionField;
        
        private string exampleField;
        
        private string authorField;
        
        private string urlField;
        
        private int defidField;
        
        /// <remarks/>
        public string word {
            get {
                return this.wordField;
            }
            set {
                this.wordField = value;
                this.RaisePropertyChanged("word");
            }
        }
        
        /// <remarks/>
        public string definition {
            get {
                return this.definitionField;
            }
            set {
                this.definitionField = value;
                this.RaisePropertyChanged("definition");
            }
        }
        
        /// <remarks/>
        public string example {
            get {
                return this.exampleField;
            }
            set {
                this.exampleField = value;
                this.RaisePropertyChanged("example");
            }
        }
        
        /// <remarks/>
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
                this.RaisePropertyChanged("author");
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        public int defid {
            get {
                return this.defidField;
            }
            set {
                this.defidField = value;
                this.RaisePropertyChanged("defid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface UrbanSearchPortTypeChannel : SkypeBot.UrbanDictionary.UrbanSearchPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class UrbanSearchPortTypeClient : System.ServiceModel.ClientBase<SkypeBot.UrbanDictionary.UrbanSearchPortType>, SkypeBot.UrbanDictionary.UrbanSearchPortType {
        
        public UrbanSearchPortTypeClient() {
        }
        
        public UrbanSearchPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UrbanSearchPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrbanSearchPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrbanSearchPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Definition[] lookup(string key, string term) {
            return base.Channel.lookup(key, term);
        }
        
        public string[] nearby(string key, string term) {
            return base.Channel.nearby(key, term);
        }
        
        public string count_definitions(string key, string term) {
            return base.Channel.count_definitions(key, term);
        }
        
        public SkypeBot.UrbanDictionary.Definition get_daily_definition() {
            return base.Channel.get_daily_definition();
        }
        
        public SkypeBot.UrbanDictionary.Definition get_random_definition(string key) {
            return base.Channel.get_random_definition(key);
        }
        
        public string[] get_related_tags(string key, string tag) {
            return base.Channel.get_related_tags(key, tag);
        }
        
        public bool verify_key(string key) {
            return base.Channel.verify_key(key);
        }
    }
}
